id: ACF3AFAF0
title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
type: translation
pechas:
- I4D1D824A
- I45D4F71B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:29.748841
  last_modified_at: 2023-01-04 11:49:29.748851
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4D1D824A/696A: 3A0A
  I45D4F71B/7D98: 3A0A
